import { Entry } from './types'

/**
 * Sorts entries by createdAt date in descending order, and filters out drafts and non-autogenerated entries
 */
export function toSortedIndex(entries: Entry[]): Entry[] {
  return entries
    .filter((entry: Entry) => {
      // keep if it should be autogenerated and not a draft
      return entry.isAutogenerated !== false && !entry.isDraft
    })
    .sort((a, b) => Number(new Date(b.createdAt)) - Number(new Date(a.createdAt)))
}
