import { MDXFileContent } from '@/v3/lib/mdx/types'

type Redirect =
  | {
      statusCode: 301 | 302 | 303 | 307 | 308
      destination: string
      basePath?: false
    }
  | {
      permanent: boolean
      destination: string
      basePath?: false
    }

export type StaticProps<EntryType> =
  | {
      props: { entry: EntryType }
      revalidate?: number | boolean
      redirect?: never
      notFound?: never
    }
  | { props?: never; revalidate?: number | boolean; redirect: Redirect; notFound?: never }
  | { props?: never; revalidate?: number | boolean; redirect?: never; notFound: true }

export enum EntryType {
  Page = 'Page',
  Article = 'Article',
}

type CommonEntryFields = {
  id: string
  type: EntryType
  title: string
  slug: string
  url: string
  createdAt: string
  updatedAt?: string
  publishedAt?: string
  isDraft?: boolean
  summary?: string
  bannerImageUrl?: string
  videoUrl?: string
  metaTitle: string
  metaDescription: string
  robots?: string
  enableComments?: boolean
  enableSharing?: boolean
  isAutogenerated?: boolean
  category?: string
  tags?: string[]
}

export type ArticleEntry = MDXFileContent<CommonEntryFields>
export type PageEntry = MDXFileContent<CommonEntryFields>
export type Entry = PageEntry | ArticleEntry
